Fix cookiecutter rendering

diff --git a/{{ cookiecutter.project_name }}/Makefile b/{{ cookiecutter.project_name }}/Makefile
--- a/{{ cookiecutter.project_name }}/Makefile
+++ b/{{ cookiecutter.project_name }}/Makefile
@@ -54,7 +54,12 @@ from-conda-lock:
 
 .PHONY: pre-commit-install
 pre-commit-install:
-	$(CONDA) pre-commit install
+	- $(CONDA) pre-commit install
+
+# Reads `pyproject.toml`, solves environment, then writes lock file.
+.PHONY: poetry-lock
+poetry-lock:
+	$(CONDA) poetry lock --no-interaction
 
 .PHONY: install
 install:
@@ -148,17 +153,39 @@ cleanup: pycache-remove dsstore-remove mypycache-remove ipynbcheckpoints-remove 
 
 
 
-###   WEBSITE   ###
+###   DOCS   ###
+
+.PHONY: docs-env
+docs-env:
+	$(CONDA) poetry install --no-interaction --only docs
+
+mkdocs_port := $(shell \
+	start_port=3000; \
+	max_attempts=100; \
+	for i in $$(seq 0 $$(($$max_attempts - 1))); do \
+		current_port=$$(($$start_port + i)); \
+		if ! lsof -i :$$current_port > /dev/null; then \
+			echo $$current_port; \
+			break; \
+		fi; \
+		if [ $$i -eq $$(($$max_attempts - 1)) ]; then \
+			echo "Error: Unable to find an available port after $$max_attempts attempts."; \
+			exit 1; \
+		fi; \
+	done \
+)
 
 .PHONY: serve
 serve:
-	echo "Served at http://127.0.0.1:8910/"
-	$(CONDA) mkdocs serve -a localhost:8910
+	echo "Served at http://127.0.0.1:$(mkdocs_port)/"
+	$(CONDA) mkdocs serve -a localhost:$(mkdocs_port)
 
 .PHONY: docs
 docs:
+	- rm -rf study/api/
 	$(CONDA) mkdocs build -d public/
-	- rm -rf 08-api/
+	- rm -rf api/
+	- rm -f public/gen_ref_pages.py
 
 .PHONY: open-docs
 open-docs:
